name: Publish to NPM

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish to NPM
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Check for changeset files
        id: check-changeset-files
        run: |
          if ls .changeset/*.md | grep '\.changeset\/[a-z-]\+\.md$'; then
            echo "has_changeset_files=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changeset_files=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Create GitHub Release
        uses: changesets/action@v1
        with:
          publish: npm run release
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
