name: Test

on:
  pull_request:
  push:
      branches:
        - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20"

      - name: install dependencies
        run: npm ci

      - name: Test
        run: npm run test
